name: Kid CI
on:
  push:
    branches: [ main, staging, sandbox, uat, master ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO CI"
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "LINT STEP"